version: '3.9'

services:

  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file: .env
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - postgres_network

  db:
    image: postgres:13.6
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres_network
      - pgadmin_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgadmin_network
    ports:
      - "5050:80"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data
  
  celery:
    build: .
    command: celery -A storefront worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A storefront beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  tests:
    build: .
    command: ptw
    depends_on:
      - web 
      - redis
      - db
    tty: true
    volumes:
      - .:/app
    networks:
      - postgres_network

volumes:
  postgresql_data:
  pgadmin:
  redisdata:    

networks:
  postgres_network:
  pgadmin_network:
    driver: bridge
