version: "3"

services:
  storefront_postgresql:
    image: postgres:13
    container_name: storefront_postgresql
    volumes:
      - storefront_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - storefront_network

volumes:
  storefront_postgresql:
    external: true

networks:
  storefront_network:
    external: true
