version: "3"

services:

  storefront_postgresql:
    image: postgres:13
    container_name: storefront_postgresql
    volumes:
      - storefront_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres
      - storefront_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1342917****
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    ports:
      - "5050:80"


volumes:
  storefront_postgresql:
    external: true
  pgadmin:

networks:
  storefront_network:
    external: true
  postgres:
    driver: bridge
